### ISSUE TITLE
[FEAT] - Updated Timestamp

### ISSUE THREAD

**Issue by naomi-lgbt** [naomi-lgbt/issues-list-api#5]
### What feature would you like to see?

We should include an updatedAt timestamp on the `/data` response, so the client can display when the issue list was last fetched from GitHub.

This will need to be added to the cache object and matching interface. It can be updated with `Date.now()` in the cache updating module.

**Comment by TAKANOME-DEV** [comment]
We can add the updateAt property in the map function of getGithubData function and it will return something like this :

![naomi](https://user-images.githubusercontent.com/79809121/168401697-76a0d351-e385-4eb6-9709-d0e38bee7272.png)

**Comment by nhcarrigan** [comment]
That would put a timestamp on every issue - we don't need that. We just need a top-level updated at.

**Comment by TAKANOME-DEV** [comment]
Ok. Well, how about this:
```ts
 app.get("/data", (_, res) => {
    const data = { ...cache, updateAt: Date.now() };
    return res.json(data);
  });
```

The result will be:

![issue list](https://user-images.githubusercontent.com/79809121/168423451-beb1fd9d-ac53-4111-bdef-a94911d0f8b2.png)

**Comment by nhcarrigan** [comment]
This would cause the updatedAt property to be the timestamp when someone makes the request, which would not be accurate.

The `updatedAt` property needs to be set when the cached list of issues is generated server side.

**Comment by TAKANOME-DEV** [comment]
What do you think about adding the `updateAt` in the `Organisations.ts`:
```diff
# getGithubData.ts
+ if (org === "updateAt") {
+    return (cache[org] = Date.now());
+  }

# Organisations.ts
export const orgList: (keyof AggregateData)[] = [
+ "updateAt", 
];

# index.ts
+ updateAt: 0,
```
The response from the frontend is the same as [above](https://github.com/nhcarrigan/issues-list-api/issues/5#issuecomment-1126694502)

**Comment by nhcarrigan** [comment]
That seems unnecessarily overengineered. I'd honestly just set it in the getGitHubData module:

https://github.com/nhcarrigan/issues-list-api/blob/a1b6b97bed9198807c1c26223c01109391f73e4e/src/modules/getGithubData.ts#L14

**Comment by TAKANOME-DEV** [comment]
I was thinking at something like that : `cach["updateAt"] = Date.now()` but TypeScript gave me an error : `Property 'updateAt' does not exist on type 'AggregateData'.`

**Comment by nhcarrigan** [comment]
Right because the interface needs to be updated to expect the new property :)

**Comment by TAKANOME-DEV** [comment]
Of course, however if we add `updateAt` in `AggregateData` interface, we should also add it in the `Organisations.ts` because  `orgList: (keyof AggregateData)[]` and that's what I did [earlier](https://github.com/nhcarrigan/issues-list-api/issues/5#issuecomment-1126799256).
If there is there another alternative, let me know 😐

**Comment by takanome-dev** [comment]
Oh silly me, I didn't know much TypeScript back then :sweat_smile: 
Nice fixed :clap: Thanks for your time and feedback :+1:
